<?php

namespace AppBundle\Repository;

/**
 * FrontEndRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrontEndRepository extends \Doctrine\ORM\EntityRepository
{
}
