<?php

namespace AppBundle\Repository;

/**
 * LecturerBibliographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecturerBibliographyRepository extends \Doctrine\ORM\EntityRepository
{
}
