<?php

namespace AppBundle\Repository;

/**
 * LecturersBibsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecturersBibsRepository extends \Doctrine\ORM\EntityRepository
{
}
