<?php

namespace AppBundle\Repository;

/**
 * MathsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MathsRepository extends \Doctrine\ORM\EntityRepository
{
}
