<?php

namespace AppBundle\Repository;

/**
 * ProposedTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProposedTagRepository extends \Doctrine\ORM\EntityRepository
{
}
