<?php

namespace AppBundle\Repository;

/**
 * ScienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScienceRepository extends \Doctrine\ORM\EntityRepository
{
}
