<?php

namespace AppBundle\Repository;

/**
 * ServerSideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerSideRepository extends \Doctrine\ORM\EntityRepository
{
}
