<?php

namespace AppBundle\Repository;

/**
 * StudentRef2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRef2Repository extends \Doctrine\ORM\EntityRepository
{
}
