<?php

namespace AppBundle\Repository;

/**
 * WebDevRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebDevRepository extends \Doctrine\ORM\EntityRepository
{
}
